# Generated by Django 5.1.4 on 2025-01-09 18:03

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Shipment",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="creation date"
                    ),
                ),
                (
                    "created_by",
                    models.UUIDField(
                        editable=False,
                        help_text="the Id of the muchmore account user who added this object",
                        null=True,
                        verbose_name="created by",
                    ),
                ),
                (
                    "last_modified_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="last modified date"
                    ),
                ),
                (
                    "last_modified_by",
                    models.UUIDField(
                        editable=False,
                        help_text="the id of the muchmore account user who last modified this object",
                        null=True,
                        verbose_name="last modified by",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="UUID primary key",
                        primary_key=True,
                        serialize=False,
                        verbose_name="id",
                    ),
                ),
                ("shipment_number", models.CharField(max_length=50, unique=True)),
                (
                    "route",
                    models.TextField(help_text="Description of the shipment route."),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("IN_TRANSIT", "In Transit"),
                            ("DELIVERED", "Delivered"),
                            ("DELAYED", "Delayed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="IN_TRANSIT",
                        max_length=20,
                    ),
                ),
                ("departure_date", models.DateTimeField(verbose_name="departure date")),
                (
                    "arrival_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="arrival date"
                    ),
                ),
                (
                    "orders",
                    models.ManyToManyField(related_name="shipments", to="orders.order"),
                ),
            ],
            options={
                "verbose_name": "shipment",
                "verbose_name_plural": "shipments",
                "ordering": ("-created_at",),
                "indexes": [
                    models.Index(
                        fields=["shipment_number"],
                        name="shipments_s_shipmen_8b3960_idx",
                    ),
                    models.Index(
                        fields=["status"], name="shipments_s_status_536511_idx"
                    ),
                ],
            },
        ),
    ]
