# Generated by Django 5.1.4 on 2025-01-09 12:58

import uuid

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "created_by",
                    models.UUIDField(
                        editable=False,
                        help_text="the Id of the muchmore account user who added this object",
                        null=True,
                        verbose_name="created by",
                    ),
                ),
                (
                    "last_modified_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="last modified date"
                    ),
                ),
                (
                    "last_modified_by",
                    models.UUIDField(
                        editable=False,
                        help_text="the id of the muchmore account user who last modified this object",
                        null=True,
                        verbose_name="last modified by",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="UUID primary key",
                        primary_key=True,
                        serialize=False,
                        verbose_name="id",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        help_text="Storage location of the item.", max_length=255
                    ),
                ),
                ("expiry_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "indexes": [
                    models.Index(fields=["name"], name="inventory_i_name_637656_idx"),
                    models.Index(
                        fields=["expiry_date"], name="inventory_i_expiry__035482_idx"
                    ),
                ],
            },
        ),
    ]
